#ifndef PROTOCOL_H
#define PROTOCOL_H
typedef unsigned int uint;
enum ENUM_MSG_TYPE{//消息类型枚举值
    ENUM_MSG_TYPE_MIN=0,
    ENUM_MSG_TYPE_REGIST_REQUEST,//1
    ENUM_MSG_TYPE_REGIST_RESPOND,//2
    ENUM_MSG_TYPE_LOGIN_REQUEST,//3
    ENUM_MSG_TYPE_LOGIN_RESPOND,//4
    ENUM_MSG_TYPE_FIND_USER_REQUEST,//5
    ENUM_MSG_TYPE_FIND_USER_RESPOND,//6
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,//7
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,//8
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,//9
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,//10
    ENUM_MSG_TYPE_AGREE_ADD_FRIEND_REQUEST,   // 11
    ENUM_MSG_TYPE_AGREE_ADD_FRIEND_RESPOND,  // 12
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,   // 13
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,  // 14
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,   // 15
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,  // 16
    ENUM_MSG_TYPE_CHAT_REQUEST,   // 17
    ENUM_MSG_TYPE_CHAT_RESPOND,  // 18
    ENUM_MSG_TYPE_MKDIR_REQUEST,   // 19
    ENUM_MSG_TYPE_MKDIR_RESPOND,  // 20
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,   // 21
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,  // 22
    ENUM_MSG_TYPE_MOVE_FILE_REQUEST,//23
    ENUM_MSG_TYPE_MOVE_FILE_RESPOND,//24
    ENUM_MSG_TYPE_UPLOAD_FILE_REQUEST,//25
    ENUM_MSG_TYPE_UPLOAD_FILE_RESPOND,//26
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUEST,//27
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,//28
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,//29
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,//30
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_REQUEST,//31
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_RESPOND,//32

    // 新增秒传相关消息类型
    ENUM_MSG_TYPE_QUERY_FILE_MD5_REQUEST,   // 33 客户端查询文件MD5是否存在
    ENUM_MSG_TYPE_QUERY_FILE_MD5_RESPOND,   // 34 服务器返回查询结果

    // 在ENUM_MSG_TYPE枚举中添加以下消息类型
    ENUM_MSG_TYPE_UPLOAD_FILE_SLICE_REQUEST,     // 35 请求上传分片
    ENUM_MSG_TYPE_UPLOAD_FILE_SLICE_RESPOND,     // 36 分片上传响应
    ENUM_MSG_TYPE_UPLOAD_FILE_COMPLETE_REQUEST,  // 37 上传完成通知
    ENUM_MSG_TYPE_UPLOAD_FILE_COMPLETE_RESPOND,  // 38 上传完成响应
    
    // 下载相关消息类型
    ENUM_MSG_TYPE_DOWNLOAD_FILE_REQUEST,         // 39 下载文件请求
    ENUM_MSG_TYPE_DOWNLOAD_FILE_RESPOND,         // 40 下载文件响应
    ENUM_MSG_TYPE_DOWNLOAD_FILE_DATA_REQUEST,    // 41 请求下载数据
    ENUM_MSG_TYPE_DOWNLOAD_FILE_DATA_RESPOND,    // 42 返回下载数据
    ENUM_MSG_TYPE_DOWNLOAD_FILE_COMPLETE_REQUEST, // 43 下载完成通知
    ENUM_MSG_TYPE_DOWNLOAD_FILE_COMPLETE_RESPOND, // 44 下载完成响应

    ENUM_MSG_TYPE_MAX=0x00fffffff,
};
struct PDU{//协议数据单元结构体
    uint uiPDULen;//协议总长度
    uint uiMsgLen;//实际消息长度（柔性数组）
    uint uiType;//消息类型
    char caData[64];//参数
    char caMsg[];//实际消息
};

struct FileInfo{
    char caName[32];
    int iType;
};

PDU* mkPDU(uint uiMsgLen = 0);
#endif // PROTOCOL_H
